services:
  jupyter:
    build: .
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/app", "--ServerApp.token=''", "--ServerApp.disable_check_xsrf=True"]

  mlflow:
    build: .
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./src:/app/src
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./mlruns"]

  airflow:
    image: apache/airflow:slim-latest
    container_name: airflow_stub
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
    command: ["webserver"]

